# Generated by Django 5.2 on 2026-09-11 16:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_platform_records'),
        ('tenants', '0017_rls_doctor_contracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.BigIntegerField(blank=True, null=True)),
                ('appointment_uuid', models.UUIDField()),
                ('patient_id', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('method', models.CharField(max_length=20)),
                ('mode', models.CharField(max_length=10)),
                ('reference', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('pending', 'بانتظار الدفع'), ('confirmed', 'مدفوع'), ('failed', 'فشل')], default='pending', max_length=10)),
                ('gateway_id', models.CharField(blank=True, default='', max_length=80)),
                ('payment_uuid', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_admin.integrationcredential')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
