# Generated by Django 5.2 on 2026-09-11 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0004_support_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keep_local', models.PositiveSmallIntegerField(default=14)),
                ('upload_to_drive', models.BooleanField(default=True)),
                ('keep_drive', models.PositiveSmallIntegerField(default=30)),
                ('include_files', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'جارٍ'), ('done', 'تم'), ('failed', 'فشل')], default='running', max_length=10)),
                ('file_name', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('groups', models.PositiveIntegerField(default=0)),
                ('drive_file_id', models.CharField(blank=True, default='', max_length=120)),
                ('drive_error', models.CharField(blank=True, default='', max_length=300)),
                ('error', models.TextField(blank=True, default='')),
                ('trigger', models.CharField(default='manual', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
