# Generated by Django 5.2 on 2026-09-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0005_backups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signuprequest',
            old_name='tenant',
            new_name='customer',
        ),
    ]
