# Generated by Django 5.2.17 on 2026-09-20 01:13

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_appointment_quantity_estimate'),
        ('branches', '0015_branch_location'),
        ('patients', '0007_patient_area_patient_consent_data_processing_at_and_more'),
        ('portal', '0003_portal_verification'),
        ('services', '0010_service_doctor_sets_quantity'),
        ('tenants', '0026_tenant_listed_in_directory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=24)),
                ('status', models.CharField(choices=[('submitted', 'بانتظار موافقة العيادة'), ('approved', 'وافقت العيادة — بانتظار اتصال خدمة العملاء'), ('contacted', 'تم الاتصال بك'), ('scheduled', 'تم تحديد الموعد'), ('rejected', 'لم توافق العيادة'), ('cancelled', 'ألغيته')], default='submitted', max_length=12)),
                ('notes', models.CharField(blank=True, default='', max_length=1000)),
                ('preferred_contact', models.CharField(blank=True, default='', max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, default='', max_length=300)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('contact_note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='branches.branch')),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='patients.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service_name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantity_unit', models.CharField(blank=True, default='', max_length=30)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_is_final', models.BooleanField(default=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='appointments.appointment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='portal.serviceorder')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='services.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['tenant', 'branch', 'status'], name='serviceorder_branch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'serial_number'), name='uniq_service_order_serial'),
        ),
    ]
