# Generated by Django 5.2.17 on 2026-09-20 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_show_publicly'),
        ('portal', '0004_service_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='payment_preference',
            field=models.CharField(choices=[('online', 'أونلاين'), ('manual', 'يدوي: تحويل أو عند الوصول')], default='manual', max_length=8),
        ),
        migrations.AddField(
            model_name='serviceorderline',
            name='preferred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorderline',
            name='preferred_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee'),
        ),
    ]
