# Generated by Django 4.2 on 2026-09-08 09:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_expense_amount_alter_expensecategory_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='expense',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='expensecategory',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='payment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paymentmethod',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
