# Generated by Django 5.2.17 on 2026-09-10 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_status_and_more'),
        ('billing', '0005_add_uuid'),
        ('branches', '0006_alter_branch_phone'),
        ('employees', '0006_alter_employee_phone1_alter_employee_phone2'),
        ('patients', '0006_alter_patient_phone1_alter_patient_phone2'),
        ('tenants', '0013_rls_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'branch', 'date'], name='expense_branch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'branch', 'date'], name='payment_branch_date_idx'),
        ),
    ]
