# Generated by Django 5.2.17 on 2026-09-19 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_discountcoupon'),
        ('branches', '0014_branch_online_cancel_notice'),
        ('tenants', '0025_tenant_portal_allow_other_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashshift',
            name='kind',
            field=models.CharField(choices=[('cashier', 'وردية موظف'), ('online', 'دفع إلكتروني')], default='cashier', max_length=10),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'online'), ('status', 'open')), fields=('tenant', 'branch'), name='one_open_online_shift_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'online'), ('user__isnull', False), _connector='OR'), name='cashier_shift_has_a_user'),
        ),
    ]
