# Generated by Django 4.2 on 2026-09-08 09:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_national_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='employeetype',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='salarytype',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='employeetype',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='salarytype',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='specialization',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
