# Generated by Django 5.2 on 2026-09-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_phone'),
        ('employees', '0007_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='extra_branches',
            field=models.ManyToManyField(blank=True, related_name='visiting_doctors', to='branches.branch'),
        ),
    ]
