# Generated by Django 5.2 on 2026-09-11 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_doctor_extra_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
