# Generated by Django 5.2 on 2026-09-11 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_doctor_commission_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pending_profile',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_review_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('pending', 'بانتظار الموافقة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='public_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
