# Generated by Django 5.2.17 on 2026-09-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_doctor_public_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='show_publicly',
            field=models.BooleanField(default=False),
        ),
    ]
