# Generated by Django 4.2 on 2026-09-08 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_create_default_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='serialcounter',
            constraint=models.UniqueConstraint(fields=('tenant', 'scope', 'date'), name='uniq_serial_counter_per_scope_day'),
        ),
    ]
