# Generated by Django 5.2.17 on 2026-09-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_rls_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='portal_show_diagnosis',
            field=models.BooleanField(default=False),
        ),
    ]
