# Generated by Django 5.2.17 on 2026-09-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_rls_intake_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='portal_self_registration',
            field=models.BooleanField(default=False),
        ),
    ]
