# Generated by Django 5.2.17 on 2026-09-19 13:24

import branches.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_rls_email_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='public_cover',
            field=models.ImageField(blank=True, null=True, upload_to=branches.media.group_upload_path),
        ),
        migrations.AddField(
            model_name='tenant',
            name='public_logo',
            field=models.ImageField(blank=True, null=True, upload_to=branches.media.group_upload_path),
        ),
    ]
