# Generated by Django 5.2.17 on 2026-09-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0024_rls_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='portal_allow_other_branches',
            field=models.BooleanField(default=False),
        ),
    ]
