import { useState } from 'react'
import { Navigate, useLocation, useNavigate } from 'react-router-dom'

import { Button, Input, Loading } from '@/components/ui'
import { LanguageToggle } from '@/components/layout/LanguageToggle'
import { ThemeToggle } from '@/components/layout/ThemeToggle'
import { useAuth } from '@/hooks/useAuth'
import { useDocumentTitle } from '@/hooks/useDebounce'

import './login.css'

export function LoginPage({ platform = false }) {
  const { login, verifyTwoFactor, isAuthenticated, isPlatform, loading } = useAuth()
  const navigate = useNavigate()
  const location = useLocation()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState(null)
  const [submitting, setSubmitting] = useState(false)
  // Platform operators: the second step (enrol or verify), then the recovery
  // codes once at enrolment.
  const [twoFactor, setTwoFactor] = useState(null)
  const [code, setCode] = useState('')
  const [recovery, setRecovery] = useState(null)

  useDocumentTitle(platform ? 'دخول بوابة المنصة' : 'تسجيل الدخول')

  if (loading) return <Loading message="جارٍ التحقق…" />

  // Someone who is already signed in and navigates here should land on the
  // application, not on a form asking them to sign in again.
  if (isPlatform && !recovery) return <Navigate to="/platform" replace />

  if (isAuthenticated) {
    return <Navigate to={location.state?.from?.pathname || '/'} replace />
  }

  const submit = async (event) => {
    event.preventDefault()
    setSubmitting(true)
    setError(null)
    try {
      const result = await login(email, password)
      if (result.twoFactor) {
        setTwoFactor(result.twoFactor)
        return
      }
      navigate(result.platform ? '/platform' : location.state?.from?.pathname || '/', {
        replace: true,
      })
    } catch (caught) {
      setError(caught.message)
    } finally {
      setSubmitting(false)
    }
  }

  const submitCode = async (event) => {
    event.preventDefault()
    setSubmitting(true)
    setError(null)
    try {
      const data = await verifyTwoFactor(code)
      if (data.recovery_codes?.length) setRecovery(data.recovery_codes)
      else navigate('/platform', { replace: true })
    } catch (caught) {
      setError(caught.message)
      if (/انتهت مهلة/.test(caught.message)) setTwoFactor(null)
    } finally {
      setSubmitting(false)
    }
  }

  if (recovery) {
    return (
      <div className="login">
        <main className="login__panel">
          <div className="login__brand">
            <h1 className="login__title">رموز الاسترداد</h1>
            <p className="login__subtitle">
              احفظها في مكان آمن الآن — لن تظهر مرة أخرى. كل رمز يُستخدم مرة واحدة إذا فقدت هاتفك.
            </p>
          </div>
          <ol className="login__codes" dir="ltr">
            {recovery.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ol>
          <Button variant="primary" block onClick={() => navigate('/platform', { replace: true })}>
            حفظتها — متابعة
          </Button>
        </main>
      </div>
    )
  }

  if (twoFactor) {
    const enrolling = twoFactor.two_factor === 'enroll'
    return (
      <div className="login">
        <main className="login__panel">
          <div className="login__brand">
            <h1 className="login__title">{enrolling ? 'تفعيل التحقق بخطوتين' : 'كود التحقق'}</h1>
            <p className="login__subtitle">
              {enrolling
                ? 'امسح الرمز بتطبيق Google Authenticator أو أي تطبيق مشابه، ثم اكتب الكود الذي يظهر.'
                : 'اكتب الكود المكوّن من ٦ أرقام من تطبيق التحقق، أو أحد رموز الاسترداد.'}
            </p>
          </div>

          {enrolling && (
            <div className="login__enrol">
              {twoFactor.qr_svg && (
                // Generated by our own server (accounts/totp.py), never user input.
                <div className="login__qr" dangerouslySetInnerHTML={{ __html: twoFactor.qr_svg }} />
              )}
              <p className="ui-muted">أو اكتب هذا المفتاح في التطبيق يدوياً:</p>
              <code className="login__secret" dir="ltr">
                {twoFactor.secret}
              </code>
            </div>
          )}

          <form className="login__form" onSubmit={submitCode}>
            {error && (
              <div className="form-error" role="alert">
                {error}
              </div>
            )}
            <Input
              id="two-factor-code"
              label="الكود"
              dir="ltr"
              inputMode="numeric"
              autoComplete="one-time-code"
              autoFocus
              required
              value={code}
              onChange={(event) => setCode(event.target.value)}
            />
            <Button type="submit" variant="primary" block loading={submitting}>
              تحقق
            </Button>
          </form>
        </main>
      </div>
    )
  }

  return (
    <div className="login">
      <div className="login__theme">
        <LanguageToggle />
        <ThemeToggle />
      </div>

      <main className="login__panel">
        <div className="login__brand">
          <span className="login__mark" aria-hidden="true">
            ⊕
          </span>
          <h1 className="login__title">{platform ? 'بوابة المنصة' : 'نظام إدارة العيادة'}</h1>
          <p className="login__subtitle">
            {platform ? 'لمشغّلي المنصة فقط — يلزم كود التحقق بعد كلمة المرور' : 'سجّل الدخول للمتابعة'}
          </p>
        </div>

        <form className="login__form" onSubmit={submit}>
          {error && (
            <div className="form-error" role="alert">
              {error}
            </div>
          )}

          <Input
            label="البريد الإلكتروني"
            type="email"
            dir="ltr"
            required
            autoFocus
            autoComplete="username"
            value={email}
            onChange={(event) => setEmail(event.target.value)}
          />

          <Input
            label="كلمة المرور"
            type="password"
            required
            autoComplete="current-password"
            value={password}
            onChange={(event) => setPassword(event.target.value)}
          />

          <Button type="submit" variant="primary" block loading={submitting}>
            تسجيل الدخول
          </Button>
        </form>

        <p className="login__note">
          إذا نسيت كلمة المرور، تواصل مع مدير العيادة لإعادة تعيينها.
        </p>
      </main>
    </div>
  )
}
