# Generated by Django 4.2 on 2026-09-08 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_add_uuid'),
        ('appointments', '0005_add_uuid'),
        ('patients', '0005_add_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0004_seed_serial_counters'),
        ('branches', '0005_add_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الزيارة')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='الشكوى')),
                ('examination', models.TextField(blank=True, verbose_name='الفحص')),
                ('diagnosis', models.TextField(blank=True, verbose_name='التشخيص')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='خطة العلاج')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='موعد المتابعة')),
                ('serial_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='appointments.appointment')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'employee_type__name': 'Doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='employees.employee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'زيارة',
                'verbose_name_plural': 'الزيارات',
                'ordering': ['-visit_date'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('substance', models.CharField(max_length=200, verbose_name='المادة')),
                ('reaction', models.CharField(blank=True, max_length=200, verbose_name='رد الفعل')),
                ('severity', models.CharField(choices=[('mild', 'خفيفة'), ('moderate', 'متوسطة'), ('severe', 'شديدة')], default='moderate', max_length=20, verbose_name='الشدة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allergies', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'حساسية',
                'verbose_name_plural': 'الحساسية',
                'ordering': ['substance'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('tenant', 'serial_number'), name='uniq_visit_serial_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='allergy',
            constraint=models.UniqueConstraint(fields=('tenant', 'patient', 'substance'), name='uniq_allergy_per_patient'),
        ),
    ]
