# Generated by Django 4.2 on 2026-09-08 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_seed_serial_counters'),
        ('patients', '0005_add_uuid'),
        ('employees', '0005_add_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الصرف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('serial_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'employee_type__name': 'Doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='employees.employee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='medical.visit')),
            ],
            options={
                'verbose_name': 'روشتة',
                'verbose_name_plural': 'الروشتات',
                'ordering': ['-issued_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('medication', models.CharField(max_length=200, verbose_name='الدواء')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='الجرعة')),
                ('frequency', models.CharField(blank=True, max_length=100, verbose_name='التكرار')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='المدة')),
                ('instructions', models.CharField(blank=True, max_length=300, verbose_name='تعليمات')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical.prescription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'دواء',
                'verbose_name_plural': 'الأدوية',
                'ordering': ['id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(fields=('tenant', 'serial_number'), name='uniq_prescription_serial_per_tenant'),
        ),
    ]
