# Generated by Django 5.2 on 2026-09-08 17:53

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid

import medical.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_add_uuid'),
        ('employees', '0005_add_uuid'),
        ('medical', '0002_prescription_prescriptionitem_and_more'),
        ('patients', '0005_add_uuid'),
        ('services', '0005_add_uuid'),
        ('tenants', '0005_row_level_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='اسم الخطة')),
                ('planned_sessions', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الجلسات المخططة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'جارية'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='active', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateField(default=medical.models.today, verbose_name='تاريخ البدء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('serial_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'employee_type__name': 'Doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to='employees.employee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='patients.patient')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to='services.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to='medical.visit')),
            ],
            options={
                'verbose_name': 'خطة علاج',
                'verbose_name_plural': 'خطط العلاج',
                'ordering': ['-start_date', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'serial_number'), name='uniq_treatment_plan_serial_per_tenant')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
