# Generated by Django 4.2 on 2026-09-08 18:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.manager
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_add_uuid'),
        ('patients', '0005_add_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0005_add_uuid'),
        ('branches', '0005_add_uuid'),
        ('services', '0005_add_uuid'),
        ('tenants', '0006_rls_covers_new_tenant_tables'),
        ('medical', '0003_treatmentplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveIntegerField(verbose_name='رقم الجلسة')),
                ('scheduled_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='موعد الجلسة')),
                ('performed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التنفيذ')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة'), ('no_show', 'لم يحضر')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الخصم')),
                ('result', models.TextField(blank=True, verbose_name='النتيجة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'employee_type__name': 'Doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_sessions', to='employees.employee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_sessions', to='patients.patient')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_sessions', to='billing.payment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='medical.treatmentplan')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_sessions', to='services.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'جلسة علاج',
                'verbose_name_plural': 'جلسات العلاج',
                'ordering': ['plan_id', 'sequence'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='treatmentsession',
            constraint=models.UniqueConstraint(fields=('tenant', 'plan', 'sequence'), name='uniq_session_sequence_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='treatmentsession',
            constraint=models.CheckConstraint(condition=models.Q(('discount__lte', django.db.models.expressions.CombinedExpression(models.F('unit_price'), '*', models.F('quantity')))), name='session_discount_within_total'),
        ),
    ]
