# Generated by Django 5.2.17 on 2026-09-09 10:01

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_add_uuid'),
        ('branches', '0006_alter_branch_phone'),
        ('employees', '0006_alter_employee_phone1_alter_employee_phone2'),
        ('medical', '0004_treatmentsession_and_more'),
        ('patients', '0006_alter_patient_phone1_alter_patient_phone2'),
        ('services', '0005_add_uuid'),
        ('tenants', '0007_rls_treatment_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الإجراء')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإجراء')),
                ('status', models.CharField(choices=[('planned', 'مخطط'), ('completed', 'تم'), ('aborted', 'توقف'), ('cancelled', 'ملغي')], default='completed', max_length=20, verbose_name='الحالة')),
                ('body_site', models.CharField(blank=True, max_length=200, verbose_name='الموضع')),
                ('findings', models.TextField(blank=True, verbose_name='ما تم ملاحظته')),
                ('outcome', models.TextField(blank=True, verbose_name='النتيجة')),
                ('complications', models.TextField(blank=True, verbose_name='مضاعفات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الخصم')),
                ('serial_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'employee_type__name': 'Doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='employees.employee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='patients.patient')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='billing.payment')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='services.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='medical.visit')),
            ],
            options={
                'verbose_name': 'إجراء',
                'verbose_name_plural': 'الإجراءات',
                'ordering': ['-performed_at', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'serial_number'), name='uniq_procedure_serial_per_tenant'), models.CheckConstraint(condition=models.Q(('discount__lte', django.db.models.expressions.CombinedExpression(models.F('unit_price'), '*', models.F('quantity')))), name='procedure_discount_within_total')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
