# Generated by Django 5.2.17 on 2026-09-09 12:33

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_phone'),
        ('employees', '0006_alter_employee_phone1_alter_employee_phone2'),
        ('medical', '0005_procedure'),
        ('patients', '0006_alter_patient_phone1_alter_patient_phone2'),
        ('tenants', '0008_rls_procedures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('test_name', models.CharField(max_length=200, verbose_name='التحليل')),
                ('specimen', models.CharField(blank=True, max_length=100, verbose_name='العينة')),
                ('lab_name', models.CharField(blank=True, max_length=200, verbose_name='المعمل')),
                ('value', models.CharField(blank=True, max_length=200, verbose_name='النتيجة')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='الوحدة')),
                ('reference_range', models.CharField(blank=True, max_length=100, verbose_name='المعدل الطبيعي')),
                ('flag', models.CharField(choices=[('normal', 'طبيعي'), ('abnormal', 'غير طبيعي'), ('critical', 'حرج')], default='normal', max_length=20, verbose_name='التقييم')),
                ('status', models.CharField(choices=[('ordered', 'مطلوب'), ('resulted', 'صدرت النتيجة'), ('cancelled', 'ملغي')], default='ordered', max_length=20, verbose_name='الحالة')),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('resulted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النتيجة')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاطلاع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('serial_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(blank=True, limit_choices_to={'employee_type__name': 'Doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='employees.employee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_results', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='medical.visit')),
            ],
            options={
                'verbose_name': 'نتيجة تحليل',
                'verbose_name_plural': 'نتائج التحاليل',
                'ordering': ['-ordered_at', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'serial_number'), name='uniq_lab_result_serial_per_tenant')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
