# Generated by Django 5.2.17 on 2026-09-09 13:14

import django.db.models.deletion
import django.db.models.manager
import medical.attachments
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_phone'),
        ('medical', '0006_labresult'),
        ('patients', '0006_alter_patient_phone1_alter_patient_phone2'),
        ('tenants', '0009_rls_lab_results'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المستند')),
                ('category', models.CharField(choices=[('lab_report', 'تقرير تحاليل'), ('imaging', 'أشعة'), ('consent', 'إقرار موافقة'), ('referral', 'إحالة'), ('clinical_photo', 'صورة إكلينيكية'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='النوع')),
                ('file', models.FileField(max_length=255, storage=medical.attachments.attachment_storage, upload_to=medical.attachments.attachment_upload_path, verbose_name='الملف')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='بصمة الملف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('serial_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('lab_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='medical.labresult')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='medical.visit')),
            ],
            options={
                'verbose_name': 'مستند طبي',
                'verbose_name_plural': 'المستندات الطبية',
                'ordering': ['-created_at', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'serial_number'), name='uniq_attachment_serial_per_tenant')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
