# Generated by Django 5.2.17 on 2026-09-10 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_medicalattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labresult',
            name='released_to_patient',
            field=models.BooleanField(default=False, verbose_name='متاح للمريض'),
        ),
        migrations.AddField(
            model_name='medicalattachment',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalattachment',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalattachment',
            name='released_to_patient',
            field=models.BooleanField(default=False, verbose_name='متاح للمريض'),
        ),
    ]
