# Generated by Django 5.2.17 on 2026-09-10 16:48

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_status_and_more'),
        ('branches', '0006_alter_branch_phone'),
        ('employees', '0007_attendance'),
        ('medical', '0008_labresult_released_at_labresult_released_by_and_more'),
        ('patients', '0006_alter_patient_phone1_alter_patient_phone2'),
        ('tenants', '0013_rls_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('smoking_status', models.CharField(blank=True, choices=[('never', 'Never smoked'), ('former', 'Former smoker'), ('current', 'Current smoker')], default='', max_length=10)),
                ('current_medications', models.TextField(blank=True)),
                ('previous_surgeries', models.TextField(blank=True)),
                ('previous_hospitalizations', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('conditions_reviewed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medical_profile', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف طبي',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('condition', models.CharField(choices=[('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('heart_disease', 'Heart disease'), ('kidney_disease', 'Kidney disease'), ('liver_disease', 'Liver disease'), ('respiratory', 'Asthma / respiratory disease'), ('thyroid', 'Thyroid disease'), ('epilepsy', 'Epilepsy'), ('blood_disorder', 'Blood disorder'), ('other', 'Other')], max_length=30)),
                ('other_name', models.CharField(blank=True, default='', max_length=100)),
                ('details', models.TextField(blank=True)),
                ('current_treatment', models.CharField(blank=True, default='', max_length=300)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conditions', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', 'condition'], name='condition_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('condition', 'other'), _negated=True), fields=('tenant', 'patient', 'condition'), name='uniq_condition_per_patient')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('case_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('acute', 'Acute complaint'), ('chronic', 'Chronic condition'), ('preventive', 'Preventive / check-up'), ('procedure', 'Procedure'), ('other', 'Other')], default='consultation', max_length=20)),
                ('reason_for_visit', models.TextField()),
                ('symptoms', models.TextField(blank=True)),
                ('symptom_onset', models.CharField(blank=True, choices=[('today', 'Today'), ('days', 'A few days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years'), ('unknown', 'Not sure')], default='', max_length=10)),
                ('reported_diagnosis', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('staff', 'Staff'), ('portal', 'Patient online')], default='staff', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to='appointments.appointment')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intakes', to='patients.patient')),
                ('requested_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_intakes', to='employees.employee')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.specialization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='intake_created_idx'), models.Index(fields=['tenant', 'case_type'], name='intake_case_type_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
