# Generated by Django 5.2 on 2026-09-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_add_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
