# Generated by Django 5.2.17 on 2026-09-19 14:51

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0012_branch_public_media'),
        ('services', '0006_service_is_active'),
        ('tenants', '0022_rls_portal_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AddField(
            model_name='service',
            name='price_display',
            field=models.CharField(choices=[('fixed', 'سعر ثابت'), ('starting_from', 'يبدأ من'), ('after_evaluation', 'بعد تقييم الطبيب')], default='fixed', max_length=20),
        ),
        migrations.CreateModel(
            name='BranchService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('online_bookable', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offers', to='branches.branch')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_offers', to='services.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', 'branch', 'is_active'], name='branchservice_branch_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'branch', 'service'), name='uniq_branch_service')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
