# Generated by Django 5.2.17 on 2026-09-19 17:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_backfill_branch_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='max_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='service',
            name='min_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='service',
            name='quantity_unit',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='requires_quantity',
            field=models.BooleanField(default=False),
        ),
    ]
