# Generated by Django 5.2.17 on 2026-09-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_service_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='doctor_sets_quantity',
            field=models.BooleanField(default=False),
        ),
    ]
