# Generated by Django 4.2 on 2026-09-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicrole',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='clinicrole',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_clinicrole_name_per_tenant'),
        ),
    ]
