# Generated by Django 4.2 on 2026-09-08 13:58

import django.contrib.auth.validators
from django.db import migrations, models
from django.utils.text import slugify


def backfill_unique_emails(apps, schema_editor):
    """Email becomes the login credential, so it has to be unique and present.

    Existing accounts were created with username as the credential, so email
    may be blank or duplicated. Anything blank or colliding gets a
    deterministic placeholder — username@tenant-slug.local — which keeps the
    account reachable (that address IS the new login) while being obviously
    a placeholder that ought to be replaced with a real address.
    """
    User = apps.get_model("accounts", "User")
    Tenant = apps.get_model("tenants", "Tenant")

    tenant_slugs = dict(Tenant.objects.values_list("id", "slug"))
    seen = set()
    generated = []

    for user in User.objects.order_by("pk").iterator():
        email = (user.email or "").strip().lower()
        if email and email not in seen:
            seen.add(email)
            if email != user.email:
                user.email = email
                user.save(update_fields=["email"])
            continue

        local = slugify(user.username) or f"user{user.pk}"
        domain = tenant_slugs.get(user.tenant_id) or "platform"
        candidate = f"{local}@{domain}.local"
        suffix = 1
        while candidate in seen:
            suffix += 1
            candidate = f"{local}-{suffix}@{domain}.local"

        seen.add(candidate)
        user.email = candidate
        user.save(update_fields=["email"])
        generated.append((user.username, candidate))

    if generated:
        print(f"\n  Generated placeholder login emails for {len(generated)} account(s):")
        for username, email in generated:
            print(f"    {username} -> {email}")
        print("  These are now the login credentials. Replace them with real addresses.")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_clinicrole_options_alter_clinicrole_managers'),
        ('tenants', '0002_create_default_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='is_platform_staff',
            field=models.BooleanField(default=False, help_text='SaaS operator rather than a member of any one clinic.'),
        ),
        # Must run before the unique constraint is applied.
        migrations.RunPython(backfill_unique_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('tenant', 'username'), name='uniq_username_per_tenant'),
        ),
    ]
