# Generated by Django 5.2 on 2026-09-11 15:49

from django.db import migrations, models


def existing_operators_are_administrators(apps, schema_editor):
    """Operators who exist today keep the full reach they have; "support" is a
    narrower role only ever given on purpose."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_platform_staff=True, platform_role="").update(platform_role="super")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_employee_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('super', 'مدير المنصة'), ('support', 'دعم فني (قراءة فقط)')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_recovery_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.RunPython(existing_operators_are_administrators, migrations.RunPython.noop),
    ]
