# Generated by Django 5.2.17 on 2026-09-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_add_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
