# Generated by Django 5.2 on 2026-09-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='intake_consent_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='branch',
            name='intake_extra_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='branch',
            name='intake_form_intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='branch',
            name='intake_form_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='branch',
            name='intake_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='print_accent_color',
            field=models.CharField(blank=True, default='#0e6e63', max_length=7),
        ),
        migrations.AddField(
            model_name='branch',
            name='print_header_subtitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='branch',
            name='print_header_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='branch',
            name='print_logo_in_footer',
            field=models.BooleanField(default=False),
        ),
    ]
