# Generated by Django 5.2 on 2026-09-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_active_and_print_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='print_links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
