# Generated by Django 5.2 on 2026-09-12 15:52

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_print_links'),
        ('tenants', '0017_rls_doctor_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='receipt_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='branch',
            name='receipt_paper_width',
            field=models.CharField(choices=[('58mm', '58 مم (تيرمال صغير)'), ('80mm', '80 مم (تيرمال قياسي)'), ('a5', 'A5')], default='80mm', max_length=4),
        ),
        migrations.AddField(
            model_name='branch',
            name='ticket_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='branch',
            name='ticket_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='branch',
            name='ticket_paper_width',
            field=models.CharField(choices=[('58mm', '58 مم (تيرمال صغير)'), ('80mm', '80 مم (تيرمال قياسي)'), ('a5', 'A5')], default='80mm', max_length=4),
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('ticket', 'تذاكر الانتظار'), ('payment', 'إيصالات الدفع'), ('expense', 'إيصالات المصروفات')], max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('mac_address', models.CharField(blank=True, default='', max_length=17, validators=[django.core.validators.RegexValidator('^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$', 'عنوان MAC غير صالح (مثال: 00:1A:2B:3C:4D:5E).')])),
                ('subnet_mask', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('dhcp', models.BooleanField(default=True)),
                ('port', models.PositiveIntegerField(default=9100)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='branches.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['branch__name', 'purpose', 'name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'branch', 'name'), name='uniq_printer_name_per_branch'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant', 'branch', 'purpose'), name='uniq_default_printer_per_branch_purpose')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
