# Generated by Django 5.2.17 on 2026-09-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_queue_ticket_and_printers'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='about_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='branch',
            name='map_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='branch',
            name='working_hours',
            field=models.TextField(blank=True, default=''),
        ),
    ]
