# Generated by Django 5.2.17 on 2026-09-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0010_branch_about_text_branch_map_url_and_more'),
        ('employees', '0010_doctor_public_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='about_hidden_specialties',
            field=models.ManyToManyField(blank=True, related_name='hidden_in_about_of', to='employees.specialization'),
        ),
        migrations.AddField(
            model_name='branch',
            name='about_visible',
            field=models.BooleanField(default=True),
        ),
    ]
