# Generated by Django 5.2.17 on 2026-09-19 13:23

import branches.media
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0011_branch_about_hidden_specialties_branch_about_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='media_review_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='branch',
            name='media_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='media_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='media_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('pending', 'بانتظار موافقة المالك'), ('rejected', 'مرفوض')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='branch',
            name='pending_public_cover',
            field=models.ImageField(blank=True, null=True, upload_to=branches.media.pending_upload_path),
        ),
        migrations.AddField(
            model_name='branch',
            name='pending_public_logo',
            field=models.ImageField(blank=True, null=True, upload_to=branches.media.pending_upload_path),
        ),
        migrations.AddField(
            model_name='branch',
            name='public_cover',
            field=models.ImageField(blank=True, null=True, upload_to=branches.media.branch_upload_path),
        ),
        migrations.AddField(
            model_name='branch',
            name='public_logo',
            field=models.ImageField(blank=True, null=True, upload_to=branches.media.branch_upload_path),
        ),
    ]
