# Generated by Django 5.2.17 on 2026-09-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0012_branch_public_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='online_booking_confirms_at_once',
            field=models.BooleanField(default=False),
        ),
    ]
