# Generated by Django 5.2.17 on 2026-09-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0013_branch_online_booking_confirms'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='online_cancel_notice_hours',
            field=models.PositiveSmallIntegerField(default=24),
        ),
    ]
