# Generated by Django 4.2 on 2026-09-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='عنوان الإيميل')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مستلم التقرير',
                'verbose_name_plural': 'مستلمو التقرير',
            },
        ),
    ]
