# Generated by Django 4.2 on 2026-09-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_add_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrecipient',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='عنوان الإيميل'),
        ),
        migrations.AddConstraint(
            model_name='reportrecipient',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='uniq_reportrecipient_email_per_tenant'),
        ),
    ]
