# Generated by Django 4.2 on 2026-09-08 09:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reportrecipient_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportrecipient',
            options={'base_manager_name': 'all_objects', 'verbose_name': 'مستلم التقرير', 'verbose_name_plural': 'مستلمو التقرير'},
        ),
        migrations.AlterModelManagers(
            name='reportrecipient',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
