# Generated by Django 4.2 on 2026-09-08 09:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='appointment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
