# Generated by Django 5.2.17 on 2026-09-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_add_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('entered', 'تم الدخول'), ('waiting', 'الانتظار'), ('called', 'تم الاتصال بالهاتف'), ('quick', 'حجز سريع'), ('requested', 'طلب من المريض')], default='waiting', max_length=20),
        ),
    ]
