# Generated by Django 5.2.17 on 2026-09-10 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_status'),
        ('branches', '0006_alter_branch_phone'),
        ('employees', '0006_alter_employee_phone1_alter_employee_phone2'),
        ('patients', '0006_alter_patient_phone1_alter_patient_phone2'),
        ('services', '0005_add_uuid'),
        ('tenants', '0013_rls_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('entered', 'تم الدخول'), ('waiting', 'الانتظار'), ('called', 'تم الاتصال بالهاتف'), ('quick', 'حجز سريع'), ('requested', 'طلب من المريض'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('no_show', 'لم يحضر')], default='waiting', max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'scheduled_date'], name='appointment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'branch', 'status'], name='appointment_branch_status_idx'),
        ),
    ]
