# Generated by Django 5.2.17 on 2026-09-18 21:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_status_and_more'),
        ('billing', '0010_discountcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='billing.discountcoupon'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
