# Generated by Django 5.2.17 on 2026-09-19 15:11

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_coupon_appointment_discount'),
        ('branches', '0012_branch_public_media'),
        ('employees', '0011_employee_show_publicly'),
        ('tenants', '0023_rls_branch_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='branches.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', 'start_date'], name='holiday_start_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='holiday_ends_after_start')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('weekday', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to='branches.branch')),
                ('doctor', models.ForeignKey(limit_choices_to={'employee_type__name': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', 'branch', 'weekday'], name='schedule_branch_day_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'doctor', 'branch', 'weekday'), name='uniq_schedule_per_day'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='schedule_ends_after_start'), models.CheckConstraint(condition=models.Q(models.Q(('break_end__isnull', True), ('break_start__isnull', True)), models.Q(('break_end__gt', models.F('break_start')), ('break_end__isnull', False), ('break_end__lte', models.F('end_time')), ('break_start__gte', models.F('start_time')), ('break_start__isnull', False)), _connector='OR'), name='schedule_break_inside_hours')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('doctor', models.ForeignKey(limit_choices_to={'employee_type__name': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', 'doctor', 'start_date'], name='timeoff_doctor_start_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='timeoff_ends_after_start')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
