# Generated by Django 5.2.17 on 2026-09-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_doctor_schedule_time_off_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('portal', 'الموقع (بوابة المرضى)'), ('reception', 'الاستقبال'), ('admin', 'الإدارة'), ('phone', 'الهاتف'), ('whatsapp', 'واتساب')], default='reception', max_length=10),
        ),
    ]
