# Generated by Django 5.2.17 on 2026-09-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_backfill_appointment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reschedule_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_requested_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
