# Generated by Django 5.2.17 on 2026-09-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_appointment_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='quantity_is_estimate',
            field=models.BooleanField(default=False),
        ),
    ]
