# Generated by Django 5.2.17 on 2026-09-09 13:57

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import subscriptions.entitlements
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0010_rls_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='الرمز')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الباقة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('billing_period', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي'), ('custom', 'عقد مخصص')], default='monthly', max_length=20, verbose_name='دورة الفوترة')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('max_branches', models.PositiveIntegerField(blank=True, null=True)),
                ('max_doctors', models.PositiveIntegerField(blank=True, null=True)),
                ('max_staff', models.PositiveIntegerField(blank=True, null=True)),
                ('max_patients', models.PositiveIntegerField(blank=True, null=True)),
                ('max_storage_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=subscriptions.entitlements.default_features)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans keep serving existing subscribers but are not offered.')),
                ('is_public', models.BooleanField(default=True, help_text='Custom contracts are not shown in the catalogue.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'باقة',
                'verbose_name_plural': 'الباقات',
                'ordering': ['price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('trial', 'تجريبي'), ('active', 'نشط'), ('past_due', 'متأخر السداد'), ('cancelled', 'ملغي'), ('expired', 'منتهي')], default='trial', max_length=20, verbose_name='الحالة')),
                ('started_on', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ البدء')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('trial_ends_on', models.DateField(blank=True, null=True, verbose_name='نهاية التجربة')),
                ('feature_overrides', models.JSONField(blank=True, default=dict, help_text='Per-tenant grants beyond the plan — §11 custom contracts.')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='الباقة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'ordering': ['-started_on', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('tenant',), name='one_active_subscription_per_tenant'), models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('started_on')), _connector='OR'), name='subscription_ends_after_it_starts')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
