# Generated by Django 5.2 on 2026-09-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_plans_and_grandfather_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='limit_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
