# Generated by Django 5.2.17 on 2026-09-10 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_phone'),
        ('employees', '0007_attendance'),
        ('patients', '0006_alter_patient_phone1_alter_patient_phone2'),
        ('tenants', '0013_rls_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='area',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_data_processing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_by_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_by_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_by_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_by_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='governorate',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='recommended_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_patients', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='patient',
            name='referral_detail',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('friend_family', 'Friend / family'), ('existing_patient', 'Existing patient'), ('doctor_referral', 'Doctor referral'), ('another_clinic', 'Another clinic'), ('hospital', 'Hospital'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('google', 'Google'), ('website', 'Website'), ('whatsapp', 'WhatsApp'), ('advertisement', 'Advertisement'), ('signage', 'Street / signage'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='referred_by_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='referring_doctor_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_source',
            field=models.CharField(choices=[('staff', 'Registered by staff'), ('portal', 'Self-registered online')], default='staff', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant', 'phone1'], name='patient_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant', 'national_id'], name='patient_nid_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant', 'referral_source'], name='patient_referral_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant', 'created_at'], name='patient_created_idx'),
        ),
    ]
