# Generated by Django 5.2.17 on 2026-09-19 12:39

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0011_branch_about_hidden_specialties_branch_about_visible'),
        ('notifications', '0005_add_uuid'),
        ('tenants', '0019_rls_portal_login_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(db_index=True, max_length=30)),
                ('to_address', models.CharField(db_index=True, max_length=254)),
                ('from_address', models.CharField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('is_html', models.BooleanField(default=False)),
                ('template', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('sent', 'أُرسلت'), ('failed', 'فشلت')], default='sent', max_length=10)),
                ('error', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='branches.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='emaillog_tenant_time')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
