# Generated by Django 5.2.17 on 2026-09-19 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_email_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='resent_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resends', to='notifications.emaillog'),
        ),
    ]
